#!/bin/bash 

echo "INFO: Running pre-push hook (run-tests)"

protected_branch='master'
repo_root=$(git rev-parse --show-toplevel)

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
  echo "INFO: No commits to push. Skipping tests."
  exit 0
fi

# Stash any uncommitted changes
git stash -q --keep-index

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ $current_branch = $protected_branch ]]; then
  for py_test in $(git ls-tree --full-tree -r --name-only HEAD | grep test.py); do
    echo -n "INFO: Running test ${py_test}..."
    test_output=$(python $repo_root/${py_test} 2>&1)
    RESULT=$?
    if [ $RESULT -ne 0 ]; then
      echo $'\e[0;31m''FAILED'$'\e[0m'
      echo "$test_output"
      echo "ERROR: Push aborted"
      echo "ERROR: Tests for ${py_test} are failing!"
      git stash pop -q
      exit 1
    fi
    echo $'\e[0;32m''PASSED'$'\e[0m'
  done
fi
git stash pop -q
exit 0
